version: '3'
services:

  server:
    build: ./server/
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  front:
    build: ./front/
    ports:
      - "4200:4200"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
